# Generated by BanglaBhasha Compiler
# Source language: BanglaBhasha

class স্ট্যাক:
    def __init__(self): self._data = []
    def ঠেলো(self, value): self._data.append(value)
    def বের_করো(self): return self._data.pop() if self._data else None
    def সামনে_দেখো(self): return self._data[-1] if self._data else None
    def খালি(self): return len(self._data) == 0
    def আকার(self): return len(self._data)

class কিউ:
    def __init__(self): self._data = []
    def ঢোকাও(self, value): self._data.append(value)
    def বের_করো_কিউ(self): return self._data.pop(0) if self._data else None
    def সামনে_দেখো_কিউ(self): return self._data[0] if self._data else None
    def খালি(self): return len(self._data) == 0
    def আকার(self): return len(self._data)

x = 10
y = 2.5
নাম = 'BanglaBhasha'
চালু = True
def যোগ(a, b):
    return (a + b)

if ((x > 5) and চালু):
    print(নাম)
    print(যোগ(x, 5))
else:
    print('শর্ত মিথ্যা')
while (x < 13):
    print(x)
    x = (x + 1)
s = স্ট্যাক()
s.ঠেলো(100)
s.ঠেলো(200)
print(s.সামনে_দেখো())
print(s.বের_করো())
q = কিউ()
q.ঢোকাও('A')
q.ঢোকাও('B')
print(q.সামনে_দেখো_কিউ())
print(q.বের_করো_কিউ())
class ব্যক্তি:
    নাম = 'অজানা'
    def নাম_সেট(self, নতুননাম):
        self.নাম = নতুননাম
    
    def পরিচয়(self):
        print(self.নাম)
    

ব্যক্তি১ = ব্যক্তি()
ব্যক্তি১.নাম_সেট('বাংলা প্রোগ্রামার')
ব্যক্তি১.পরিচয়()
